import re
with open('lib/screens/custom_recipe_screen.dart', 'r', encoding='utf-8') as f:
    content = f.read()

content = content.replace('extraIngredients: extra,', 'extraIngredients: _extraIngredientsController.text,')

content = content.replace('String extra = _extraIngredientsController.text;\n    if (_hiddenAiExtra != null && AppStrings.str(lang, _hiddenAiExtra!) == extra) {\n      extra = _hiddenAiExtra!;\n    }\n    \n    final coffee = double.tryParse(_coffeeController.text) ?? 15.0;\n    final water = double.tryParse(_waterController.text) ?? 250.0;\n    final time = int.tryParse(_timeController.text) ?? 150;\n\n    final phases = _mutablePhases.map((mp) {\n      PhaseAction action = mp['action'] ?? PhaseAction.pourCircle;\n      return RecipePhase(\n        startTimeSeconds: mp['start'],\n        pourAmountMl: (action == PhaseAction.pourCircle || action == PhaseAction.pourCenter) ? mp['amount'] : 0.0,\n        action: action,\n      );\n    }).toList();\n\n    final recipe = Recipe(\n      id: saveAsNew ? null : widget.initialRecipe?.id,\n      name: name,\n      description: note,\n      coffeeGrams: coffee,\n      totalWaterMl: water,\n      totalDurationSeconds: time,\n      phases: phases,\n      targetGrindSizeMicrons: _targetGrindSizeMicrons,\n      beanType: _beanType,\n      extraIngredients: _extraIngredientsController.text,', 'String extra = _extraIngredientsController.text;\n    if (_hiddenAiExtra != null && AppStrings.str(lang, _hiddenAiExtra!) == extra) {\n      extra = _hiddenAiExtra!;\n    }\n    \n    final coffee = double.tryParse(_coffeeController.text) ?? 15.0;\n    final water = double.tryParse(_waterController.text) ?? 250.0;\n    final time = int.tryParse(_timeController.text) ?? 150;\n\n    final phases = _mutablePhases.map((mp) {\n      PhaseAction action = mp['action'] ?? PhaseAction.pourCircle;\n      return RecipePhase(\n        startTimeSeconds: mp['start'],\n        pourAmountMl: (action == PhaseAction.pourCircle || action == PhaseAction.pourCenter) ? mp['amount'] : 0.0,\n        action: action,\n      );\n    }).toList();\n\n    final recipe = Recipe(\n      id: saveAsNew ? null : widget.initialRecipe?.id,\n      name: name,\n      description: note,\n      coffeeGrams: coffee,\n      totalWaterMl: water,\n      totalDurationSeconds: time,\n      phases: phases,\n      targetGrindSizeMicrons: _targetGrindSizeMicrons,\n      beanType: _beanType,\n      extraIngredients: extra,')

with open('lib/screens/custom_recipe_screen.dart', 'w', encoding='utf-8') as f:
    f.write(content)
