// AUTO-GENERATED from lib/core/recipe.dart (recipeDatabase).
// Do not hand-edit: regenerate with `python expo/scripts/convert_recipes.py`
// so the Flutter and Expo builds stay identical on brewing values.
import type { RecipeSeed } from './recipe';

export const recipeSeeds: RecipeSeed[] = [
  {
    isBuiltIn: true,
    name: "James Hoffmann Ultimate V60",
    description: "desc_key_0",
    coffeeGrams: 15,
    totalWaterMl: 250,
    totalDurationSeconds: 210,
    method: 'v60',
    targetGrindSizeMicrons: 800,
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 50, action: 'pourCenter'},
          {startTimeSeconds: 10, action: 'swirl'},
          {startTimeSeconds: 15, action: 'wait'},
          {startTimeSeconds: 45, pourAmountMl: 100, action: 'pourCircle'},
          {startTimeSeconds: 75, pourAmountMl: 100, action: 'pourCircle'},
          {startTimeSeconds: 105, action: 'swirl'},
          {startTimeSeconds: 110, action: 'wait'},
        ],
  },
  {
    isBuiltIn: true,
    name: "Tetsu Kasuya 4-6 Method",
    description: "desc_key_1",
    coffeeGrams: 20,
    totalWaterMl: 300,
    totalDurationSeconds: 210,
    method: 'v60',
    targetGrindSizeMicrons: 1100,
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 50, action: 'pourCircle'},
          {startTimeSeconds: 45, pourAmountMl: 70, action: 'pourCircle'},
          {startTimeSeconds: 90, pourAmountMl: 60, action: 'pourCircle'},
          {startTimeSeconds: 135, pourAmountMl: 60, action: 'pourCircle'},
          {startTimeSeconds: 180, pourAmountMl: 60, action: 'pourCircle'},
        ],
  },
  {
    isBuiltIn: true,
    name: "Osmotic Flow",
    description: "desc_key_2",
    coffeeGrams: 20,
    totalWaterMl: 300,
    totalDurationSeconds: 180,
    method: 'v60',
    targetGrindSizeMicrons: 750,
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 30, action: 'pourCenter'},
          {startTimeSeconds: 30, pourAmountMl: 90, action: 'pourCenter'},
          {startTimeSeconds: 60, pourAmountMl: 60, action: 'pourCenter'},
          {startTimeSeconds: 90, pourAmountMl: 60, action: 'pourCenter'},
          {startTimeSeconds: 120, pourAmountMl: 60, action: 'pourCenter'},
        ],
  },
  {
    isBuiltIn: true,
    name: "April Pour-Over",
    description: "desc_key_3",
    coffeeGrams: 13,
    totalWaterMl: 200,
    totalDurationSeconds: 150,
    method: 'v60',
    targetGrindSizeMicrons: 900,
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 30, action: 'pourCircle'},
          {startTimeSeconds: 5, pourAmountMl: 70, action: 'pourCenter'},
          {startTimeSeconds: 35, pourAmountMl: 30, action: 'pourCircle'},
          {startTimeSeconds: 40, pourAmountMl: 70, action: 'pourCenter'},
        ],
  },
  {
    isBuiltIn: true,
    name: "Scott Rao V60",
    description: "desc_key_4",
    coffeeGrams: 20,
    totalWaterMl: 300,
    totalDurationSeconds: 180,
    method: 'v60',
    targetGrindSizeMicrons: 800,
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 60, action: 'pourCircle'},
          {startTimeSeconds: 5, action: 'swirl'},
          {startTimeSeconds: 10, action: 'wait'},
          {startTimeSeconds: 45, pourAmountMl: 240, action: 'pourCircle'},
          {startTimeSeconds: 90, action: 'swirl'},
          {startTimeSeconds: 95, action: 'wait'},
        ],
  },
  {
    isBuiltIn: true,
    name: "Hario Official V60",
    description: "desc_key_5",
    coffeeGrams: 12,
    totalWaterMl: 120,
    totalDurationSeconds: 120,
    method: 'v60',
    targetGrindSizeMicrons: 700,
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 30, action: 'pourCircle'},
          {startTimeSeconds: 30, pourAmountMl: 90, action: 'pourCircle'},
        ],
  },
{
    isBuiltIn: true,
    name: "Hario Switch (Tetsu Kasuya)",
    description: "desc_key_6",
    coffeeGrams: 20,
    totalWaterMl: 300,
    totalDurationSeconds: 150,
    method: 'v60',
    targetGrindSizeMicrons: 800,
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 150, action: 'pourCircle'},
          {startTimeSeconds: 65, action: 'closeValve'},
          {startTimeSeconds: 75, pourAmountMl: 150, action: 'pourCircle'},
          {startTimeSeconds: 120, action: 'openValve'},
        ],
  },
  {
    isBuiltIn: true,
    name: "Clever Dripper / Full Immersion",
    description: "desc_key_7",
    coffeeGrams: 15,
    totalWaterMl: 250,
    totalDurationSeconds: 180,
    method: 'v60',
    targetGrindSizeMicrons: 850,
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 250, action: 'pourCenter'},
          {startTimeSeconds: 40, action: 'wait'},
          {startTimeSeconds: 120, action: 'stir'},
          {startTimeSeconds: 130, action: 'wait'},
          {startTimeSeconds: 150, action: 'openValve'},
        ],
  },

  // ====================================
  // FRENCH PRESS RECIPES (Total 10)
  // ====================================,
  {
    isBuiltIn: true,
    name: "James Hoffmann French Press",
    description: "desc_key_8",
    coffeeGrams: 30,
    totalWaterMl: 500,
    totalDurationSeconds: 570,
    method: 'frenchPress',
    targetGrindSizeMicrons: 900,
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 500, action: 'pourCenter'},
          {startTimeSeconds: 240, action: 'stir'},
          {startTimeSeconds: 250, action: 'wait'},
          {startTimeSeconds: 540, action: 'press'},
        ],
  },
  {
    isBuiltIn: true,
    name: "Traditional French Press",
    description: "desc_key_9",
    coffeeGrams: 30,
    totalWaterMl: 500,
    totalDurationSeconds: 270,
    method: 'frenchPress',
    targetGrindSizeMicrons: 1100,
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 500, action: 'pourCenter'},
          {startTimeSeconds: 60, action: 'stir'},
          {startTimeSeconds: 70, action: 'wait'},
          {startTimeSeconds: 240, action: 'press'},
        ],
  },
  {
    isBuiltIn: true,
    name: "Cafe au Lait (Strong French Press)",
    description: "desc_key_10",
    coffeeGrams: 30,
    totalWaterMl: 300,
      extraIngredients: "extra_key_0",
    totalDurationSeconds: 270,
    method: 'frenchPress',
    targetGrindSizeMicrons: 1000,
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 300, action: 'pourCenter'},
          {startTimeSeconds: 60, action: 'stir'},
          {startTimeSeconds: 70, action: 'wait'},
          {startTimeSeconds: 240, action: 'press'},
        ],
  },
  {
    isBuiltIn: true,
    name: "Lance Hedrick French Press",
    description: "desc_key_11",
    coffeeGrams: 30,
    totalWaterMl: 500,
    totalDurationSeconds: 330,
    method: 'frenchPress',
    targetGrindSizeMicrons: 800,
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 500, action: 'pourCenter'},
          {startTimeSeconds: 30, action: 'stir'},
          {startTimeSeconds: 40, action: 'wait'},
          {startTimeSeconds: 300, action: 'press'},
        ],
  },
  {
    isBuiltIn: true,
    name: "Slayer French Press (Skim Early)",
    description: "desc_key_12",
    coffeeGrams: 30,
    totalWaterMl: 500,
    totalDurationSeconds: 270,
    method: 'frenchPress',
    targetGrindSizeMicrons: 950,
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 500, action: 'pourCenter'},
          {startTimeSeconds: 60, action: 'stir'},
          {startTimeSeconds: 70, action: 'wait'},
          {startTimeSeconds: 240, action: 'press'},
        ],
  },
  {
    isBuiltIn: true,
    name: "French Press Cold Water Bloom",
    description: "desc_key_13",
      coffeeGrams: 30,
      totalWaterMl: 500,
      totalDurationSeconds: 330,
      method: 'frenchPress',
      targetGrindSizeMicrons: 1000,
      phases: [
          {startTimeSeconds: 0, pourAmountMl: 50, action: 'pourCenter'},
          {startTimeSeconds: 60, pourAmountMl: 450, action: 'pourCenter'},
          {startTimeSeconds: 300, action: 'press'},
        ],
    },
  {
    isBuiltIn: true,
    name: "Tim Wendelboe French Press",
    description: "desc_key_14",
      coffeeGrams: 30,
      totalWaterMl: 500,
      totalDurationSeconds: 570,
      method: 'frenchPress',
      targetGrindSizeMicrons: 1000,
      phases: [
          {startTimeSeconds: 0, pourAmountMl: 500, action: 'pourCenter'},
          {startTimeSeconds: 240, action: 'stir'},
          {startTimeSeconds: 250, action: 'wait'},
          {startTimeSeconds: 540, action: 'press'},
        ],
    },

  // ====================================
  // AEROPRESS RECIPES (Total 10)
  // ====================================,
  {
    isBuiltIn: true,
    name: "Alan Adler (Original)",
      extraIngredients: "extra_key_1",
      description: "desc_key_15",
      coffeeGrams: 15,
      totalWaterMl: 60,
    totalDurationSeconds: 90,
    method: 'aeropress',
    targetGrindSizeMicrons: 500,
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 60, action: 'pourCenter'},
          {startTimeSeconds: 15, action: 'stir'},
          {startTimeSeconds: 25, action: 'press'},
        ],
  },
  {
    isBuiltIn: true,
    name: "Tim Wendelboe Aeropress",
    description: "desc_key_16",
    coffeeGrams: 14,
    totalWaterMl: 200,
    totalDurationSeconds: 80,
    method: 'aeropress',
    targetGrindSizeMicrons: 700,
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 200, action: 'pourCenter'},
          {startTimeSeconds: 15, action: 'stir'},
          {startTimeSeconds: 18, action: 'wait'},
            {startTimeSeconds: 20, action: 'cap'},
          {startTimeSeconds: 25, action: 'wait'},
          {startTimeSeconds: 60, action: 'press'},
        ],
  },
  {
    isBuiltIn: true,
    name: "James Hoffmann Ultimate Aeropress",
    description: "desc_key_17",
    coffeeGrams: 11,
    totalWaterMl: 200,
    totalDurationSeconds: 180,
    method: 'aeropress',
    targetGrindSizeMicrons: 650,
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 200, action: 'pourCenter'},
          {startTimeSeconds: 15, action: 'cap'},
          {startTimeSeconds: 19, action: 'wait'},
          {startTimeSeconds: 25, action: 'wait'},
          {startTimeSeconds: 120, action: 'swirl'},
          {startTimeSeconds: 125, action: 'wait'},
          {startTimeSeconds: 150, action: 'press'},
        ],
  },
  {
    isBuiltIn: true,
    name: "Inverted Classic",
    description: "desc_key_18",
    coffeeGrams: 15,
    totalWaterMl: 200,
    totalDurationSeconds: 150,
    method: 'aeropress',
    targetGrindSizeMicrons: 700,
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 200, action: 'pourCenter'},
          {startTimeSeconds: 30, action: 'stir'},
          {startTimeSeconds: 33, action: 'wait'},
            {startTimeSeconds: 40, action: 'cap'},
          {startTimeSeconds: 45, action: 'wait'},
          {startTimeSeconds: 90, action: 'flip'},
          {startTimeSeconds: 95, action: 'wait'},
          {startTimeSeconds: 120, action: 'press'},
        ],
  },
  {
    isBuiltIn: true,
    name: "Aeropress Espresso Concentrate",
    description: "desc_key_19",
    coffeeGrams: 18,
    totalWaterMl: 90,
    totalDurationSeconds: 120,
    method: 'aeropress',
    targetGrindSizeMicrons: 450,
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 90, action: 'pourCenter'},
          {startTimeSeconds: 30, action: 'stir'},
          {startTimeSeconds: 33, action: 'wait'},
            {startTimeSeconds: 40, action: 'cap'},
          {startTimeSeconds: 45, action: 'wait'},
          {startTimeSeconds: 70, action: 'flip'},
          {startTimeSeconds: 75, action: 'wait'},
          {startTimeSeconds: 90, action: 'press'},
        ],
  },
  {
    isBuiltIn: true,
    name: "Aeropress Milk Punch",
    description: "desc_key_20",
    coffeeGrams: 18,
    totalWaterMl: 80,
    extraIngredients: "extra_key_2",
    totalDurationSeconds: 120,
    method: 'aeropress',
    targetGrindSizeMicrons: 500,
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 80, action: 'pourCenter'},
          {startTimeSeconds: 30, action: 'stir'},
          {startTimeSeconds: 33, action: 'wait'},
            {startTimeSeconds: 40, action: 'cap'},
          {startTimeSeconds: 45, action: 'wait'},
          {startTimeSeconds: 90, action: 'press'},
        ],
  },
  {
    isBuiltIn: true,
    name: "WAC 2023 Champion Recipe",
    description: "desc_key_21",
      coffeeGrams: 16,
      totalWaterMl: 220,
      totalDurationSeconds: 150,
      method: 'aeropress',
      targetGrindSizeMicrons: 600,
      extraIngredients: "extra_key_3",
      phases: [
          {startTimeSeconds: 0, pourAmountMl: 140, action: 'pourCenter'},
          {startTimeSeconds: 10, action: 'swirl'},
          {startTimeSeconds: 15, action: 'wait'},
          {startTimeSeconds: 90, action: 'press'},
          {startTimeSeconds: 115, action: 'wait'},
          {startTimeSeconds: 120, pourAmountMl: 80, action: 'pourCenter'},
        ],
    },
  {
    isBuiltIn: true,
    name: "Jonathan Gagne Long Steep",
    description: "desc_key_22",
      coffeeGrams: 20,
      totalWaterMl: 300,
      totalDurationSeconds: 570,
      method: 'aeropress',
      targetGrindSizeMicrons: 800,
      phases: [
          {startTimeSeconds: 0, pourAmountMl: 300, action: 'pourCenter'},
          {startTimeSeconds: 540, action: 'press'},
        ],
    },
  {
      isBuiltIn: true,
      name: "Aeropress Iced Coffee",
      description: "desc_key_23",
      coffeeGrams: 18,
      totalWaterMl: 100,
      totalDurationSeconds: 90,
      method: 'aeropress',
      targetGrindSizeMicrons: 400,
      extraIngredients: "extra_key_4",
      phases: [
          {startTimeSeconds: 0, pourAmountMl: 100, action: 'pourCenter'},
          {startTimeSeconds: 10, action: 'swirl'},
          {startTimeSeconds: 14, action: 'wait'},
          {startTimeSeconds: 20, action: 'cap'},
          {startTimeSeconds: 25, action: 'wait'},
          {startTimeSeconds: 60, action: 'press'},
        ],
    },
  {
    isBuiltIn: true,
    name: "Aeropress Espresso (Faux-Presso)",
    description: "desc_key_24",
      coffeeGrams: 18,
      totalWaterMl: 50,
      totalDurationSeconds: 90,
      method: 'aeropress',
      targetGrindSizeMicrons: 400,
      phases: [
          {startTimeSeconds: 0, pourAmountMl: 50, action: 'pourCenter'},
          {startTimeSeconds: 10, action: 'swirl'},
          {startTimeSeconds: 14, action: 'wait'},
          {startTimeSeconds: 20, action: 'cap'},
          {startTimeSeconds: 25, action: 'wait'},
          {startTimeSeconds: 60, action: 'press'},
        ],
    },

  // ====================================
  // VIETNAM DRIP RECIPES (Total 10)
  // ====================================,
  {
    isBuiltIn: true,
    name: "Tradisional Vietnam Drip",
    description: "desc_key_25",
    coffeeGrams: 15,
      beanType: "Robusta",
    totalWaterMl: 120,
    extraIngredients: "extra_key_7",
    totalDurationSeconds: 300,
    method: 'vietnamDrip',
    targetGrindSizeMicrons: 800,
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 20, action: 'pourCenter'},
          {startTimeSeconds: 30, pourAmountMl: 100, action: 'pourCenter'},
        ],
  },
  {
    isBuiltIn: true,
    name: "Ca Phe Sua Da (Kopi Susu Es)",
    description: "desc_key_26",
    coffeeGrams: 20,
      beanType: "Robusta",
    totalWaterMl: 100,
    extraIngredients: "extra_key_5",
    totalDurationSeconds: 300,
    method: 'vietnamDrip',
    targetGrindSizeMicrons: 750,
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 20, action: 'pourCenter'},
          {startTimeSeconds: 40, pourAmountMl: 80, action: 'pourCenter'},
        ],
  },
  {
    isBuiltIn: true,
    name: "Ca Phe Den (Kopi Hitam)",
    description: "desc_key_27",
    coffeeGrams: 15,
    totalWaterMl: 150,
    totalDurationSeconds: 300,
    method: 'vietnamDrip',
    targetGrindSizeMicrons: 900,
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 25, action: 'pourCenter'},
          {startTimeSeconds: 40, pourAmountMl: 125, action: 'pourCenter'},
        ],
  },
  {
    isBuiltIn: true,
    name: "Modern Specialty Drip",
    description: "desc_key_28",
    coffeeGrams: 15,
    totalWaterMl: 225,
    totalDurationSeconds: 240,
    method: 'vietnamDrip',
    targetGrindSizeMicrons: 850,
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 40, action: 'pourCenter'},
          {startTimeSeconds: 45, pourAmountMl: 185, action: 'pourCenter'},
        ],
  },
  {
    isBuiltIn: true,
    name: "Drip Ristretto Style",
    description: "desc_key_29",
    coffeeGrams: 20,
    totalWaterMl: 60,
    totalDurationSeconds: 300,
    method: 'vietnamDrip',
    targetGrindSizeMicrons: 700,
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 60, action: 'pourCenter'},
        ],
  },
  {
    isBuiltIn: true,
    name: "Vietnam Drip Gula Aren",
    description: "desc_key_30",
    coffeeGrams: 18,
      beanType: "Robusta",
    totalWaterMl: 130,
    extraIngredients: "extra_key_6",
    totalDurationSeconds: 300,
    method: 'vietnamDrip',
    targetGrindSizeMicrons: 800,
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 30, action: 'pourCenter'},
          {startTimeSeconds: 40, pourAmountMl: 100, action: 'pourCenter'},
        ],
  },
  {
    isBuiltIn: true,
    name: "Vietnam Drip Paper Filter Method",
    description: "desc_key_31",
    coffeeGrams: 15,
      beanType: "Robusta",
    totalWaterMl: 120,
    totalDurationSeconds: 300,
    method: 'vietnamDrip',
    targetGrindSizeMicrons: 800,
    extraIngredients: "extra_key_7",
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 20, action: 'pourCenter'},
          {startTimeSeconds: 30, pourAmountMl: 100, action: 'pourCenter'},
        ],
  },
  {
    isBuiltIn: true,
    name: "Specialty High-Ratio Drip (1:12)",
    description: "desc_key_32",
    coffeeGrams: 15,
    totalWaterMl: 180,
    totalDurationSeconds: 240,
    method: 'vietnamDrip',
    targetGrindSizeMicrons: 1000,
    extraIngredients: "",
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 30, action: 'pourCenter'},
          {startTimeSeconds: 30, pourAmountMl: 150, action: 'pourCenter'},
        ],
  },
  {
    isBuiltIn: true,
    name: "Double Tamp Vietnam Drip",
    description: "desc_key_33",
      coffeeGrams: 20,
      beanType: "Robusta",
      totalWaterMl: 100,
      totalDurationSeconds: 360,
      method: 'vietnamDrip',
      targetGrindSizeMicrons: 800,
      extraIngredients: "",
      phases: [
          {startTimeSeconds: 0, pourAmountMl: 20, action: 'pourCenter'},
          {startTimeSeconds: 30, action: 'press'},
          {startTimeSeconds: 35, action: 'wait'},
          {startTimeSeconds: 45, pourAmountMl: 80, action: 'pourCenter'},
        ],
    },

  // ====================================
  // CUPPING RECIPES (Total 10)
  // ====================================,
  {
    isBuiltIn: true,
    name: "SCA Cupping Protocol",
    description: "desc_key_34",
    coffeeGrams: 11,
    totalWaterMl: 200,
    totalDurationSeconds: 660,
    method: 'cupping',
      beanType: 'Bebas',
    targetGrindSizeMicrons: 850,
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 200, action: 'pourCenter'},
          {startTimeSeconds: 240, action: 'stir'},
          {startTimeSeconds: 245, action: 'wait'},
          {startTimeSeconds: 600, action: 'wait'},
        ],
  },
  {
    isBuiltIn: true,
    name: "James Hoffmann Home Cupping",
    description: "desc_key_35",
    coffeeGrams: 12,
    totalWaterMl: 200,
    totalDurationSeconds: 750,
    method: 'cupping',
      beanType: 'Bebas',
    targetGrindSizeMicrons: 850,
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 200, action: 'pourCenter'},
          {startTimeSeconds: 240, action: 'stir'},
          {startTimeSeconds: 245, action: 'wait'},
          {startTimeSeconds: 720, action: 'wait'},
        ],
  },
  {
    isBuiltIn: true,
    name: "Cold Evaluation Cupping",
    description: "desc_key_36",
    coffeeGrams: 11,
    totalWaterMl: 200,
    totalDurationSeconds: 930,
    method: 'cupping',
      beanType: 'Bebas',
    targetGrindSizeMicrons: 850,
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 200, action: 'pourCenter'},
          {startTimeSeconds: 240, action: 'stir'},
          {startTimeSeconds: 250, action: 'wait'},
          {startTimeSeconds: 900, action: 'wait'},
        ],
  },
  {
    isBuiltIn: true,
    name: "Minimal Agitation Cupping",
    description: "desc_key_37",
      coffeeGrams: 12,
      totalWaterMl: 200,
      totalDurationSeconds: 750,
      method: 'cupping',
      beanType: 'Bebas',
      targetGrindSizeMicrons: 800,
      phases: [
          {startTimeSeconds: 0, pourAmountMl: 200, action: 'pourCenter'},
          {startTimeSeconds: 720, action: 'wait'},
        ],
    },

  // ====================================
  // COLD BREW RECIPES (Total 10)
  // ====================================,
  {
    isBuiltIn: true,
    name: "Japanese Iced Coffee (Fruity)",
    description: "desc_key_38",
    coffeeGrams: 15, totalWaterMl: 150,
      extraIngredients: "extra_key_8", totalDurationSeconds: 150,
    method: 'v60', targetGrindSizeMicrons: 700, beanType: 'Arabica',
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 50, action: 'pourCenter'},
          {startTimeSeconds: 40, pourAmountMl: 100, action: 'pourCircle'},
        ],
  },
  {
    isBuiltIn: true,
    name: "Japanese Iced Coffee (Sweet)",
    description: "desc_key_39",
    coffeeGrams: 15, totalWaterMl: 150,
      extraIngredients: "extra_key_9", totalDurationSeconds: 180,
    method: 'v60', targetGrindSizeMicrons: 750, beanType: 'Arabica',
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 40, action: 'pourCenter'},
          {startTimeSeconds: 45, pourAmountMl: 55, action: 'pourCircle'},
          {startTimeSeconds: 90, pourAmountMl: 55, action: 'pourCircle'},
        ],
  },


  {
    isBuiltIn: true,
    name: "Ryan Wibawa WBrC 2024",
    description: "desc_key_40",
    coffeeGrams: 16, totalWaterMl: 240, totalDurationSeconds: 160,
    method: 'v60', targetGrindSizeMicrons: 800, beanType: 'Arabica',
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 50, action: 'pourCenter'},
          {startTimeSeconds: 40, pourAmountMl: 70, action: 'pourCircle'},
          {startTimeSeconds: 80, pourAmountMl: 60, action: 'pourCircle'},
          {startTimeSeconds: 110, pourAmountMl: 60, action: 'pourCircle'},
        ],
  },
  {
    isBuiltIn: true,
    name: "Yoshua Tanu Fast Flow",
    description: "desc_key_41",
    coffeeGrams: 15, totalWaterMl: 225, totalDurationSeconds: 120,
    method: 'v60', targetGrindSizeMicrons: 900, beanType: 'Arabica',
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 45, action: 'pourCircle'},
          {startTimeSeconds: 5, action: 'swirl'},
          {startTimeSeconds: 10, action: 'wait'},
          {startTimeSeconds: 30, pourAmountMl: 90, action: 'pourCircle'},
          {startTimeSeconds: 70, pourAmountMl: 90, action: 'pourCircle'},
          {startTimeSeconds: 80, action: 'swirl'},
          {startTimeSeconds: 85, action: 'wait'},
        ],
  },
  {
    isBuiltIn: true,
    name: "Orea V3/Kalita Wave",
    description: "desc_key_42",
    coffeeGrams: 15, totalWaterMl: 250, totalDurationSeconds: 150,
    method: 'v60', targetGrindSizeMicrons: 800, beanType: 'Arabica',
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 50, action: 'pourCenter'},
          {startTimeSeconds: 40, pourAmountMl: 100, action: 'pourCenter'},
          {startTimeSeconds: 80, pourAmountMl: 100, action: 'pourCenter'},
        ],
  },

  {
    isBuiltIn: true,
    name: "V60 Dark Roast (Low Temp)",
    description: "desc_key_43",
    coffeeGrams: 15, totalWaterMl: 250, totalDurationSeconds: 140,
    method: 'v60', targetGrindSizeMicrons: 900, beanType: 'Blend',
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 50, action: 'pourCenter'},
          {startTimeSeconds: 45, pourAmountMl: 100, action: 'pourCenter'},
          {startTimeSeconds: 85, pourAmountMl: 100, action: 'pourCenter'},
        ],
  },

  {
    isBuiltIn: true,
    name: "Kasuya Devil Recipe (Switch)",
    description: "desc_key_44",
    coffeeGrams: 20, totalWaterMl: 280, totalDurationSeconds: 200,
    method: 'v60', targetGrindSizeMicrons: 850, beanType: 'Arabica',
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 60, action: 'pourCenter'},
          {startTimeSeconds: 40, action: 'closeValve'},
          {startTimeSeconds: 42, pourAmountMl: 120, action: 'pourCenter'},
          {startTimeSeconds: 80, pourAmountMl: 100, action: 'pourCircle'},
          {startTimeSeconds: 120, action: 'openValve'},
        ],
  },

  {
    isBuiltIn: true,
    name: "W.A.C Carolina Ibarra (2018)",
    description: "desc_key_45",
    coffeeGrams: 35, totalWaterMl: 100, totalDurationSeconds: 90,
    method: 'aeropress', targetGrindSizeMicrons: 800, beanType: 'Arabica',
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 100, action: 'pourCenter'},
          {startTimeSeconds: 30, action: 'stir'},
          {startTimeSeconds: 33, action: 'wait'},
            {startTimeSeconds: 40, action: 'cap'},
          {startTimeSeconds: 46, action: 'wait'},
          {startTimeSeconds: 55, action: 'flip'},
          {startTimeSeconds: 60, action: 'press'},
        ],
  },

  {
    isBuiltIn: true,
    name: "W.A.C Paulina Miczka (2017)",
    description: "desc_key_46",
    coffeeGrams: 35, totalWaterMl: 150, totalDurationSeconds: 105,
    method: 'aeropress', targetGrindSizeMicrons: 850, beanType: 'Arabica',
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 150, action: 'pourCenter'},
          {startTimeSeconds: 15, action: 'stir'},
          {startTimeSeconds: 25, action: 'wait'},
          {startTimeSeconds: 35, action: 'stir'},
          {startTimeSeconds: 38, action: 'wait'},
            {startTimeSeconds: 45, action: 'cap'},
          {startTimeSeconds: 51, action: 'wait'},
          {startTimeSeconds: 70, action: 'flip'},
          {startTimeSeconds: 75, action: 'press'},
        ],
  },

  {
    isBuiltIn: true,
    name: "Tuomas Merikanto W.A.C",
    description: "desc_key_47",
    coffeeGrams: 18, totalWaterMl: 200, totalDurationSeconds: 150,
    method: 'aeropress', targetGrindSizeMicrons: 750, beanType: 'Arabica',
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 50, action: 'pourCenter'},
          {startTimeSeconds: 10, action: 'swirl'},
          {startTimeSeconds: 15, action: 'wait'},
          {startTimeSeconds: 45, pourAmountMl: 150, action: 'pourCenter'},
          {startTimeSeconds: 90, action: 'press'},
        ],
  },

  {
    isBuiltIn: true,
    name: "Aeropress Flow Control",
    description: "desc_key_48",
    coffeeGrams: 18, totalWaterMl: 250, totalDurationSeconds: 150,
    method: 'aeropress', targetGrindSizeMicrons: 700, beanType: 'Arabica',
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 250, action: 'pourCenter'},
          {startTimeSeconds: 30, action: 'stir'},
          {startTimeSeconds: 40, action: 'wait'},
          {startTimeSeconds: 120, action: 'press'},
        ],
  },

  {
    isBuiltIn: true,
    name: "Aeropress Espresso Fake",
    description: "desc_key_49",
    coffeeGrams: 20, totalWaterMl: 60, totalDurationSeconds: 90,
    method: 'aeropress', targetGrindSizeMicrons: 300, beanType: 'Blend',
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 60, action: 'pourCenter'},
          {startTimeSeconds: 20, action: 'stir'},
          {startTimeSeconds: 30, action: 'wait'},
          {startTimeSeconds: 60, action: 'press'},
        ],
  },

  {
    isBuiltIn: true,
    name: "Aeropress Tea-like Extract",
    description: "desc_key_50",
    coffeeGrams: 12, totalWaterMl: 250, totalDurationSeconds: 180,
    method: 'aeropress', targetGrindSizeMicrons: 1000, beanType: 'Arabica',
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 250, action: 'pourCenter'},
          {startTimeSeconds: 150, action: 'press'},
        ],
  },

  {
    isBuiltIn: true,
    name: "Aeropress Robusta Sweet",
    description: "desc_key_51",
    coffeeGrams: 15, totalWaterMl: 60,
      extraIngredients: "extra_key_10", totalDurationSeconds: 120,
    method: 'aeropress', targetGrindSizeMicrons: 700, beanType: 'Robusta',
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 60, action: 'pourCenter'},
          {startTimeSeconds: 30, action: 'stir'},
          {startTimeSeconds: 40, action: 'wait'},
          {startTimeSeconds: 90, action: 'press'},
        ],
  },

  {
    isBuiltIn: true,
    name: "Ca Phe Muoi (Salted Coffee)",
    description: "desc_key_52",
    coffeeGrams: 20,
      extraIngredients: "extra_key_11", totalWaterMl: 100, totalDurationSeconds: 300,
    method: 'vietnamDrip', targetGrindSizeMicrons: 650, beanType: 'Robusta',
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 20, action: 'pourCenter'},
          {startTimeSeconds: 30, pourAmountMl: 80, action: 'pourCenter'},
        ],
  },

  {
    isBuiltIn: true,
    name: "Ca Phe Trung (Egg Coffee)",
    description: "desc_key_53",
    coffeeGrams: 20,
      extraIngredients: "extra_key_12", totalWaterMl: 80, totalDurationSeconds: 300,
    method: 'vietnamDrip', targetGrindSizeMicrons: 650, beanType: 'Robusta',
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 20, action: 'pourCenter'},
          {startTimeSeconds: 45, pourAmountMl: 60, action: 'pourCenter'},
        ],
  },

  {
    isBuiltIn: true,
    name: "Ca Phe Sua Chua (Yogurt Coffee)",
    description: "desc_key_54",
    coffeeGrams: 15,
      extraIngredients: "extra_key_13", totalWaterMl: 100, totalDurationSeconds: 240,
    method: 'vietnamDrip', targetGrindSizeMicrons: 700, beanType: 'Robusta',
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 20, action: 'pourCenter'},
          {startTimeSeconds: 30, pourAmountMl: 80, action: 'pourCenter'},
        ],
  },

  {
    isBuiltIn: true,
    name: "Phin Arabica Light",
    description: "desc_key_55",
    coffeeGrams: 15, totalWaterMl: 120, totalDurationSeconds: 240,
    method: 'vietnamDrip', targetGrindSizeMicrons: 800, beanType: 'Arabica',
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 30, action: 'pourCenter'},
          {startTimeSeconds: 45, pourAmountMl: 90, action: 'pourCenter'},
        ],
  },

  {
    isBuiltIn: true,
    name: "Vietnam Drip Mocha",
    description: "desc_key_56",
    coffeeGrams: 15,
      extraIngredients: "extra_key_14", totalWaterMl: 100, totalDurationSeconds: 300,
    method: 'vietnamDrip', targetGrindSizeMicrons: 700, beanType: 'Blend',
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 20, action: 'pourCenter'},
          {startTimeSeconds: 30, pourAmountMl: 80, action: 'pourCenter'},
        ],
  },

  {
    isBuiltIn: true,
    name: "Phin Coconut (Bac Xiu)",
    description: "desc_key_57",
    coffeeGrams: 15,
    totalWaterMl: 60,
    totalDurationSeconds: 300,
    method: 'vietnamDrip',
    targetGrindSizeMicrons: 700,
    beanType: 'Robusta',
    extraIngredients: "extra_key_15",
    phases: [
          {startTimeSeconds: 0, pourAmountMl: 20, action: 'pourCenter'},
          {startTimeSeconds: 45, pourAmountMl: 40, action: 'pourCenter'},
        ],
  }

];
