class AppStrings {
  static const Map<String, Map<String, String>> _strings = {
    'id': {
      'grinder_clicks': 'klik',
      'header_favorites': 'â­ Favorit',
      'header_custom': 'âœ¨ Resep Buatanmu',
      'header_builtin': 'â˜• Resep Standar',
      'mark_favorite': 'Tandai sebagai favorit',
      'remove_favorite': 'Hapus dari favorit',
      // AUTO GENERATED ID RECIPES
      'desc_key_0': 'Gunakan air 99Â°C dan gilingan medium-fine. Buat divot (lubang kecil) di tengah kopi. Goyangkan (swirl) alat seduh di fase bloom dan setelah tuangan terakhir untuk meratakan ekstraksi.\n\nEstimasi Rasa: Ekstraksi seimbang (balanced), manis yang optimal, dan clarity (kejernihan rasa) yang tinggi.',
      'desc_key_1': 'Gunakan gilingan kasar (coarse) dan air 90-92Â°C. Biarkan air turun sepenuhnya (bed kering) sebelum lanjut ke tuangan berikutnya. 40% air pertama mengatur asam/manis, 60% sisanya mengatur kepekatan.\n\nEstimasi Rasa: Sangat jernih (clean cup), acidity (keasaman) terang, dengan body yang ringan (tea-like).',
      'desc_key_2': 'Gilingan medium-fine. Air 90-92Â°C. Tuang air sangat perlahan hanya di area tengah sebesar koin logam. JANGAN biarkan air mengenai kertas. Jaga kubah kopi (coffee dome) tetap utuh.\n\nEstimasi Rasa: Sangat manis (sweetness maksimal), body lembut dan tebal, dengan acidity yang diredam.',
      'desc_key_3': 'Gunakan suhu rendah (sekitar 90Â°C) dan gilingan coarse. Tuang melingkar lambat tanpa agitasi keras. Disarankan menggunakan dripper flat-bed.\n\nEstimasi Rasa: Keasaman (acidity) yang sangat cerah, clean cup, dan rasa buah yang menonjol.',
      'desc_key_4': 'Buat lubang (divot) di tengah. Gunakan suhu tinggi. Lakukan \'Rao Spin\' (goyangkan dripper melingkar) setelah bloom dan di akhir untuk meratakan bed ampas kopi dan mencegah channeling.\n\nEstimasi Rasa: Ekstraksi seimbang (high extraction yield), manis, minim astringency.',
      'desc_key_5': 'Resep klasik bawaan pabrik Hario. Sangat ramah pemula. Tuang perlahan secara memutar dari tengah ke luar, lalu kembali ke tengah.\n\nEstimasi Rasa: Klasik, body sedang, acidity menonjol, dan aroma seduh yang kuat.',
      'desc_key_6': 'God Recipe Tetsu Kasuya. Suhu 90Â°C. BUKA keran di awal (perkolasi). Di detik ke-65, TUTUP keran (imersi). BUKA keran lagi di akhir. Menghasilkan ekstraksi balance sempurna.\n\nEstimasi Rasa: Sangat manis, perpaduan unik antara kejernihan V60 dan body dari imersi.',
      'desc_key_7': 'Gilingan medium. Tuang air terlebih dahulu, lalu masukkan bubuk kopi. Aduk setelah beberapa saat, lalu diamkan (steep).\n\nEstimasi Rasa: Body penuh, rasa sangat seimbang, dan minim risiko over-ekstraksi.',
      'desc_key_8': 'Gilingan medium (tidak perlu terlalu kasar). Seduh selama 4 menit, lalu aduk kerak kopi di permukaan. Bersihkan busa (skim). Tunggu lagi 5-8 menit sebelum menuang, dan JANGAN menekan plunger sampai bawah.\n\nEstimasi Rasa: Body penuh namun sangat jernih tanpa ampas, tekstur kental, dan rasa seimbang.',
      'desc_key_9': 'Gilingan coarse (kasar). Tuang seluruh air, aduk merata. Diamkan selama 4 menit, lalu tekan plunger perlahan sampai dasar.\n\nEstimasi Rasa: Body sangat tebal, aroma kuat, tekstur berpasir/kotor (gritty) klasik.',
      'desc_key_10': 'Seduh kopi sangat pekat. Campurkan dengan susu panas yang di steam atau dihangatkan dengan rasio 1:1.\n\nEstimasi Rasa: Hangat, milky, gurih susu dengan karakter kopi yang tetap kuat.',
      'desc_key_11': 'Gilingan sedang-halus. Langsung aduk merata dengan sendok di awal. Diamkan 5 menit. Tekan plunger HANYA sampai menyentuh air agar serbuk halus tetap tertahan di bawah.\n\nEstimasi Rasa: Sangat bersih untuk French Press, body lembut, rasa manis yang diekstrak perlahan.',
      'desc_key_12': 'Aduk kuat di awal dan langsung buang busa di menit pertama agar ekstraksi merata sejak awal.\n\nEstimasi Rasa: Body tebal namun minim partikel halus (grit), rasa lebih clean dari tradisional.',
      'desc_key_13': 'Pra-seduh dengan air suhu ruang selama 1 menit, lalu tuang air panas. Menurunkan rasa pahit dan meningkatkan kemanis alami kopi.\n\nEstimasi Rasa: Menurunkan acidity tajam dan pahit (bitterness), menonjolkan profil manis yang lebih lembut.',
      'desc_key_14': 'Mirip cupping. Seduh 4 menit, aduk perlahan, buang busa dan kerak, tunggu 5 menit lagi baru ditekan.\n\nEstimasi Rasa: Cita rasa Nordic roast (terang), acidity cerah, body ringan, lebih mirip cupping bowl.',
      'desc_key_15': '[Metode: Standard] Gunakan kertas filter. Air suhu 80Â°C (sangat rendah). Aduk cepat selama 10 detik, lalu tekan perlahan. Jangan menekan sampai mendesis.\n\nEstimasi Rasa: Sangat manis, acidity rendah, body tebal, mirip espresso concentrate.',
      'desc_key_16': '[Metode: Standard] Gilingan medium-fine. Air mendidih. Seduh normal (non-inverted). Aduk perlahan, lalu tekan perlahan di detik ke 60.\n\nEstimasi Rasa: Clean cup, acidity cerah, rasa mirip pour-over filter V60.',
      'desc_key_17': '[Metode: Standard] Lebih hemat kopi. Posisi standar. Seduh 2 menit, putar sedikit, diamkan 30 detik, lalu tekan perlahan.\n\nEstimasi Rasa: Sangat efisien, manis, body penuh, dan ekstraksi merata tanpa asam berlebih.',
      'desc_key_18': '[Metode: Inverted] (WAJIB Posisi Terbalik / Inverted). Tuang air, aduk kuat dengan sendok, lalu tutup. Di menit 1:30, balikkan alat ke atas gelas perlahan dan tekan turun.\n\nEstimasi Rasa: Body kuat, rasa pekat (bold), cocok untuk dicampur susu atau diminum murni.',
      'desc_key_19': '[Metode: Inverted] Ekstrak pekat untuk campuran susu. Posisi terbalik. Kopi digiling sangat halus, air sangat sedikit.\n\nEstimasi Rasa: Sangat pekat, asam dan pahit terkonsentrasi, cocok sebagai bahan dasar kopi susu.',
      'desc_key_20': '[Metode: Standard] Seduh kopi sangat pekat (concentrate) (Gunakan alat Prismo / Flow Control) lalu aduk langsung dengan susu dingin dan es batu di dalam gelas.\n\nEstimasi Rasa: Milk punch yang lembut, creamy, dan segar.',
      'desc_key_21': '[Metode: Standard] Resep juara dunia Aeropress 2023. Ekstraksi suhu rendah dengan pengadukan intens, lalu dicampur air panas di akhir (bypass).\n\nEstimasi Rasa: Kompleks, manis, acidity buah cerah namun tekstur sangat lembut (silky).',
      'desc_key_22': '[Metode: Standard] Durasi panjang 9 menit dengan gilingan seukuran V60. Menghasilkan ekstraksi manis dan merata tanpa kepahitan.\n\nEstimasi Rasa: Ekstraksi sangat tinggi (high EY), manis maksimal, tidak ada rasa asam under-extracted.',
      'desc_key_23': '[Metode: Standard] Gunakan metode inverted atau standar. Air mendidih untuk mengekstrak konsentrat kopi. Aduk merata, lalu tekan ke atas gelas yang berisi bongkahan es.\n\nEstimasi Rasa: Segar, pekat di awal namun mencair perlahan (refreshing), manis.',
      'desc_key_24': '[Metode: Standard] Gilingan sangat halus dengan air sangat sedikit, ditekan sekuat tenaga. Menghasilkan konsentrat pekat mirip espresso.\n\nEstimasi Rasa: Kuat, pekat (punchy), crema buatan (jika ditekan keras), cocok untuk mocktail/susu.',
      'desc_key_25': 'Gilingan medium-coarse. Kopi Robusta gelap. Padatkan dengan saringan tekan. Tuang air mendidih. Proses tetesan memakan waktu sekitar 5-6 menit.\n\nEstimasi Rasa: Pahit pekat, smokey, body sangat kental (syrupy) dan kuat.',
      'desc_key_26': 'Letakkan kental manis di dasar gelas. Kopi Robusta diteteskan langsung di atasnya. Setelah selesai, aduk merata, lalu tuangkan ke gelas berisi es batu.\n\nEstimasi Rasa: Manis karamel yang intens, gurih susu, kopi pekat yang menendang, tekstur creamy.',
      'desc_key_27': 'Vietnam Drip tanpa susu kental manis. Rasio air dibuat lebih panjang dan gilingan lebih kasar agar tidak pahit.\n\nEstimasi Rasa: Sangat pahit, kuat, dominan rasa coklat gelap/kacang sangrai, syrupy.',
      'desc_key_28': 'Pendekatan modern untuk biji kopi sangrai terang. Mengekstrak rasa asam manis dengan bersih.\n\nEstimasi Rasa: Lebih jernih dari tradisional, acidity mulai muncul, kompleksitas rasa modern.',
      'desc_key_29': 'Kopi ditekan sangat padat, air panas sedikit. Tetesan super intens bagai sirup kopi tebal.\n\nEstimasi Rasa: Sangat pekat dan pendek, intensitas tinggi, pahit manis menghentak.',
      'desc_key_30': 'Kombinasi klasik Susu Kental Manis (SKM) dan Sirup Gula Aren. SKM memberikan tekstur \'creamy\' khas Vietnam Drip, sementara aren memberikan aroma legit karamel. Tuang SKM dan aren di dasar gelas, seduh perlahan, aduk rata lalu tambahkan es.\n\nEstimasi Rasa: Sangat creamy, manis legit aren berpadu dengan rasa kopi yang kuat dan tebal.',
      'desc_key_31': 'Menggunakan kertas saring (seukuran Aeropress) di dasar alat Phin sebelum kopi dimasukkan. Menghasilkan seduhan super bersih tanpa ampas halus. (Opsional: letakkan satu kertas lagi di atas kopi sebelum tamper untuk ekstraksi super merata).\n\nEstimasi Rasa: Jauh lebih bersih (clean) tanpa ampas, body berkurang namun flavor lebih jelas.',
      'desc_key_32': 'Dikhususkan untuk biji kopi specialty (Light Roast), proses tamping tidak terlalu padat agar air mengalir optimal.\n\nEstimasi Rasa: Rasio yang lebih panjang menghasilkan minuman yang lebih ringan, mirip pour-over pekat.',
      'desc_key_33': 'Metode langka: Tekan kopi dengan saringan, tuang air bloom, lalu tekan LAGI (tamp kedua) sebelum menuang sisa air. Menghasilkan tetesan yang jauh lebih lambat.\n\nEstimasi Rasa: Intensitas ekstrak luar biasa, seperti espresso, body sangat tebal.',
      'desc_key_34': 'Suhu 93Â°C. Di menit ke-4, dorong punggung sendok cupping sebanyak 3 kali ke permukaan kopi (break the crust). Bersihkan sisa busanya. Mulai seruput di menit ke-10 saat suhu turun.\n\nEstimasi Rasa: Profil rasa murni dari biji kopi untuk keperluan evaluasi cacat/kualitas.',
      'desc_key_35': 'Cupping ala rumahan. Gunakan dua sendok untuk membuang busa di menit ke-4.\n\nEstimasi Rasa: Rasa murni biji kopi tanpa gangguan filter kertas, sangat cocok untuk membandingkan 2 biji.',
      'desc_key_36': 'Evaluasi fokus di rasa kopi saat sangat dingin di menit ke-15. Fase awal sama, namun tunggu sangat lama.\n\nEstimasi Rasa: Menilai rasa kopi saat suhu ruang (menonjolkan sweetness atau justru defect/asam kecut).',
      'desc_key_37': 'Tanpa proses memecah kerak. Kopi dibiarkan turun sendiri perlahan ke dasar gelas. Menghasilkan evaluasi rasa yang sangat bersih.\n\nEstimasi Rasa: Sangat clean, ekstraksi lebih pelan menghindari kepahitan (astringency) berlebih.',
      'desc_key_38': 'Gilingan medium-fine. Tuang air panas ke kopi, tetesan akan langsung mengenai es batu di dalam server untuk mengunci aroma volatile. \n\nEstimasi Rasa: Acidity buah yang sangat tajam, segar, dan aromatik (floral/fruity).',
      'desc_key_39': 'Sama dengan Japanese Iced Coffee, namun rasio es batu disesuaikan dan tuangan dibagi untuk memaksimalkan manis. \n\nEstimasi Rasa: Lebih manis dan balance, tidak terlalu asam, body sedikit lebih tebal.',
      'desc_key_40': 'Adaptasi resep Juara 3 World Brewers Cup 2024. Menggunakan 4 fase tuangan yang volumenya mengecil di akhir untuk mencegah ekstraksi berlebih. Menghasilkan rasa yang balance dan syrupy.\n\nEstimasi Rasa: Rasa berlapis (layered), kompleksitas tinggi, manis aromatik yang elegan.',
      'desc_key_41': 'Suhu tinggi (93Â°C). Tuang air sangat deras (fast flow). Goyang/swirl dripper lumayan agresif di awal agar semua bubuk basah merata. Selesai super singkat di 2 menit.\n\nEstimasi Rasa: Acidity buah yang sangat transparan, ringan, mirip teh manis rasa kopi.',
      'desc_key_42': 'Tuangan konsisten untuk dripper datar (flat bed). Menyoroti acidity dan kebersihan rasa.\n\nEstimasi Rasa: Tingkat kemanisan luar biasa berkat flat bed, ekstraksi konsisten, balance.',
      'desc_key_43': 'Gunakan air suhu 85C dan tuangan cepat di tengah untuk menghindari rasa gosong dan pahit berlebih pada biji sangrai gelap.\n\nEstimasi Rasa: Pahit yang lembut (smooth), manis karamel, tanpa rasa gosong/asap berlebih.',
      'desc_key_44': 'Devil Recipe V60 Switch. BUKA keran di awal. WAJIB gunakan air SUHU RUANG (dingin/biasa) untuk fase Bloom 60ml pertama. Sisanya, gunakan air sangat mendidih untuk fase imersi.\n\nEstimasi Rasa: Sangat berani, ekstraksi manis pekat di awal, ditutup dengan imersi untuk body.',
      'desc_key_45': '[Metode: Inverted] Resep juara dunia Aeropress 2018. Posisi inverted, aduk kuat, hasilkan ekstraksi yang super fruity.\n\nEstimasi Rasa: Ceria (vibrant), acidity menyala, bersih (clean finish).',
      'desc_key_46': '[Metode: Inverted] Resep juara 2017. Rasio 1:5 pekat di awal, ditambah air bypass di akhir. Inverted.\n\nEstimasi Rasa: Bulat (round body), seimbang, sangat enak untuk kopi natural.',
      'desc_key_47': '[Metode: Standard] Aeropress standar (tidak inverted). Air 80C, biarkan menetes perlahan lalu press sangat lambat.\n\nEstimasi Rasa: Kompleks, dominan manis, body juicy.',
      'desc_key_48': '[Metode: Standard] Menggunakan cap Prismo atau Flow Control. Imersi penuh tanpa inverted.\n\nEstimasi Rasa: Seperti espresso rumahan, pekat, tidak ada kebocoran air sebelum waktunya.',
      'desc_key_49': '[Metode: Standard] Ekstraksi konsentrat tinggi yang menyerupai espresso. Gunakan Prismo/Flow Control dan gilingan espresso.\n\nEstimasi Rasa: Pahit, tebal, pekat, cocok dicampur gula merah atau susu.',
      'desc_key_50': '[Metode: Standard] Rasio renggang dan gilingan kasar untuk rasa kopi yang mirip teh dan menyegarkan.\n\nEstimasi Rasa: Sangat ringan, tembus pandang, rasa bunga/buah dominan layaknya teh premium.',
      'desc_key_51': '[Metode: Standard] Khusus untuk kopi Robusta. Ekstraksi singkat dengan suhu 85C agar tidak terlalu pahit.\n\nEstimasi Rasa: Pahit khas Robusta namun diimbangi tekstur kental dan rasa nutty yang manis.',
      'desc_key_52': 'Buat krim garam dengan mengocok susu kental manis, susu cair/krim, dan garam hingga berbusa. Teteskan kopi di atasnya. Aduk sebelum diminum.\n\nEstimasi Rasa: Kombinasi menakjubkan antara asin gurih, manis kental, dan pahit kopi pekat. Umami!',
      'desc_key_53': 'Kocok kuning telur ayam kampung dengan susu kental manis dan sedikit madu hingga mengembang menjadi busa kental. Teteskan kopi panas di atas/bawahnya.\n\nEstimasi Rasa: Sangat creamy, mirip dessert (tiramisu), manis kental, tanpa amis telur.',
      'desc_key_54': 'Kombinasi unik Vietnam. Masukkan yogurt di dasar gelas, tambahkan kental manis, seduh kopi di atasnya, tambahkan es batu.\n\nEstimasi Rasa: Asam segar yogurt berpadu dengan manis creamy dan pahit kopi. Sangat menyegarkan.',
      'desc_key_55': 'Vietnam Drip khusus untuk biji Arabica. Sedikit dipadatkan, suhu 92C untuk body tebal nan fruity.\n\nEstimasi Rasa: Asam buah (fruity) khas Arabica, body tidak terlalu tebal dibanding Robusta.',
      'desc_key_56': 'Tambahkan bubuk kakao atau sirup coklat ke dalam kental manis. Teteskan kopi menembus coklat. Aduk rata.\n\nEstimasi Rasa: Coklat pekat (dark chocolate), manis, tebal, mirip permen kopi cokelat.',
      'desc_key_57': 'Varian kopi susu es Vietnam (Báº¡c Xá»‰u) dengan tambahan santan. Proporsi susu dan kelapa jauh lebih mendominasi dibandingkan kopinya untuk rasa manis, gurih, dan creamy.\n\nEstimasi Rasa: Manis gurih kelapa, sangat creamy, rasa kopi lebih lembut di latar belakang.',
      'extra_key_0': 'Susu Panas (150ml)',
      'extra_key_1': '140ml Air panas tambahan (Bypass)',
      'extra_key_2': 'Susu Cair Dingin (100ml), Es Batu (100g)',
      'extra_key_3': 'Siapkan 80 ml air panas di gelas saji (untuk bypass)',
      'extra_key_4': 'Es batu (sekitar 100g)',
      'extra_key_5': 'Susu Kental Manis (30g), Es Batu (150g)',
      'extra_key_6': 'Susu Kental Manis (15-20ml), Sirup Gula Aren (10-15ml), Es Batu',
      'extra_key_7': '30 ml susu kental manis',
      'extra_key_8': 'Es Batu (100g di server)',
      'extra_key_9': 'Es Batu (90g di server)',
      'extra_key_10': 'Air panas/es tambahan untuk bypass',
      'extra_key_11': 'Krim Asin (Susu 20ml, SKM 10g, Sejumput Garam), Es Batu (100g)',
      'extra_key_12': 'Kuning Telur (1 butir), SKM (20g), Madu (1 sdt)',
      'extra_key_13': 'Yogurt Plain (50g), SKM (15g), Es Batu (100g)',
      'extra_key_14': 'Sirup Cokelat/Kakao (15g), SKM (20g)',
      'extra_key_15': '40 ml susu kental manis, 60 ml santan cair (atau susu kelapa), 100 gram es batu. (Campur semua di gelas penampung)',


      'brew_dose': 'Takar Kopi: {0} sendok',
      'brew_grind': 'Gilingan',
      'brew_bean': 'Jenis Biji Kopi',
      'brew_extra': 'Bahan Tambahan',
      'brew_desc_title': 'Deskripsi Resep:',
      'rotations_half': ' setengah',
      'custom_grind_400': 'Sangat Halus (Espresso)',
      'custom_grind_600': 'Halus (Aeropress)',
      'custom_grind_800': 'Sedang (V60 / Kalita)',
      'custom_grind_1000': 'Agak Kasar (Chemex)',
      'custom_grind_1200': 'Kasar (French Press / Switch)',
      'custom_grind_1400': 'Sangat Kasar (Cold Brew)',
      'custom_bean_blend': 'Blend (Campuran)',
      'custom_bean_bebas': 'Bebas (Semua)',
      'custom_recipe_desc': 'Deskripsi Resep',
      'custom_recipe_extra_hint': 'Misal: 15 ml susu kental manis, 100 gram es batu',


      'home_select_method': 'Pilih Metode Seduh:',
      'method_v60_desc': 'Penyeduhan tuang dengan putaran spiral',
      'method_fp_desc': 'Penyeduhan rendam tanpa ampas',
      'method_ap_desc': 'Penyeduhan tekan dengan tekanan udara',
      'method_vd_desc': 'Penyeduhan tetes pelan (Kopi Susu)',
      'method_cup_desc': 'Standar internasional evaluasi kopi',


      'calib_guide': 'Panduan Kalibrasi:\n1. Siapkan teko kopi berisi air, dan timbangan atau gelas takar.\n2. Aktifkan tombol Simulasi Metronom di bawah.\n3. Setelah aba-aba mulai, tuang air seperti biasa.\n4. Hitung ada berapa bunyi TIK yang terdengar sampai air mencapai target mililiter yang kamu inginkan.\n5. Coba tuang sambil memutar teko, lalu hitung butuh berapa bunyi TIK untuk menyelesaikan satu putaran penuh.\n6. Masukkan angka-angka tersebut ke dalam kolom di bawah!',
      'calib_header': 'Pengaturan Alat Seduh dan Kalibrasi Debit Air',
      'calib_q1': 'Berapa ml/gram gelas takar atau target tuanganmu?',
      'calib_q2': 'Nyalakan metronom lalu tuang air. Berapa detik/ketukan yang dibutuhkan sampai target tercapai?',
      'calib_q3': 'Biasanya kamu butuh berapa detik untuk 1 putaran penuh saat menuang melingkar?',
      'toggle_api_key': 'Tampilkan atau sembunyikan API Key',
      'restore_success': 'Resep bawaan berhasil dikembalikan!',
      'calib_grinder_select': 'Pilih Grinder Kopimu:',
      'calib_grinder_title': 'Pilih Grinder',
      'calib_grinder_manual': 'Grinder Manual',
      'calib_grinder_electric': 'Grinder Elektrik',
      'calib_spoon_q': 'Berapa gram kapasitas sendok takar kopimu?',
      'calib_sim_btn': 'Simulasi Metronom (Mainkan Hitung Mundur)',
      
      'ai_greet_edit': "Halo! Aku lihat kamu sedang mengedit resep '{0}'. Ada yang mau diubah?",
      'ai_greet_new': "Halo! Mau meracik resep seduhan seperti apa hari ini?",
      'ai_error_general': "Maaf, terjadi kesalahan saat memproses permintaanmu.",
      'ai_hint': "Ketik pesan...",
      'ai_voice_note': '\u{1F399}\u{FE0F} [Pesan Suara]',
      'ai_apply_btn': "Terapkan ke Form",
      'ai_send_label': "Kirim pesan teks",
      'ai_record_start_label': "Mulai rekam suara",
      'ai_record_stop_label': "Hentikan rekaman",
      'ai_coffee': "Kopi",
      'ai_water': "Air",
      'ai_time': "Waktu",
      
      'tts_preview_btn': "Coba Dengarkan Suara",
      'tts_preview_text': "Ini adalah contoh suara dari pengaturan saat ini.",
      
      'action_swirl': 'Swirl perlahan',
      'action_cap': 'Pasang Tutup',
      'action_flip': 'Balikkan ke atas gelas',
      
      'ai_chat_title': 'Rancang Bersama AI',

      'app_title': 'SenseBrew',
      'settings_menu': 'Menu Pengaturan Aplikasi',
      'calibrate_flow_rate': 'Pengaturan Alat Seduh dan Kalibrasi Debit Air',
      'settings_title': 'Pengaturan',
      'settings_restore_title': 'Pulihkan Resep Bawaan',
      'settings_restore_sub': 'Kembalikan resep bawaan yang terhapus',
      
      'theme_title': 'Tema Tampilan',
      'calibrated_status': 'Alat siap. Debit air: {0} ml per detik',
      'uncalibrated_status': 'Debit air belum dikalibrasi.',
      'calibrated_btn': '{0} ml/detik',
      'uncalibrated_btn': '(Wajib dilakukan)',
      'custom_recipe_btn': 'Buat Resep\nKustom',
      'custom_recipe_label': 'Buat resep seduh kustom.',
      'recipe_label': 'Resep {0}. {1} gram kopi. {2} mililiter air.',
      'calib_title': 'Pengaturan Alat Seduh dan Kalibrasi Debit Air',      'stop_metronome': 'Hentikan Metronom',
      'start_metronome': 'Mainkan Metronom',
      'save_calib': 'SIMPAN KALIBRASI',
      'save_calib_label': 'Simpan hasil kalibrasi',
      'save_success': 'Kalibrasi berhasil disimpan.',

      'pour_calc_title': 'Kalkulator Tuang',
      'pour_calc_desc': 'Alat bantu tuang bebas. Masukkan jumlah air (ml) yang ingin dituang, aplikasi akan menghitung dan memandu waktunya berdasarkan kalibrasi teko Anda.',
      'pour_calc_target': 'Target Tuangan (ml)',
      'pour_calc_est': 'Estimasi Waktu: {0} detik',
      'pour_calc_start': 'Mulai Tuang',
      'pour_calc_stop': 'Berhenti',
      'pour_calc_ready': 'Siap-siap, tuang dalam',

      'reduce': 'Kurangi menjadi {0} {1}',
      'add': 'Tambah menjadi {0} {1}',
      'custom_title': 'Buat Resep Kustom',
      'recipe_name': 'Nama Resep',
      'recipe_note': 'Catatan & Aturan Seduh',
      'coffee_grams': 'Kopi (gram)',
      'total_water': 'Total Air (mililiter)',
      'total_time': 'Total Waktu (detik)',
      'phases_title': 'Tahapan Seduh',
      'start_sec': 'Mulai di Detik Ke-',
      'water_ml': 'Jumlah Air (mililiter)',
      'add_phase': 'Tambah Tahapan',
      'delete_phase': 'Hapus Tahapan',
      'save_recipe': 'SIMPAN RESEP',
      'save_as_new': 'Simpan Sebagai Resep Baru',
      'save_overwrite': 'Simpan Perubahan (Timpa)',
      'save_recipe_success': 'Resep kustom berhasil disimpan.',
      'brew_sec': 'Detik: {0}\n{1}',
      'brew_title': 'Resep {0}\nKopi: {1} gram\nAir: {2} ml',
      'note_label': 'Catatan dan aturan seduh: {0}',
      'note': 'Catatan: {0}',
      'brew_phases': 'Tahapan Seduh:',
      'brew_phase_item_circle': 'â€¢ Detik ke-{0}: Tuang {1} ml ({2} putaran)',
      'brew_phase_item_center': 'â€¢ Detik ke-{0}: Tuang {1} ml ({2} detik)',
      'brew_phase_item_stir': 'â€¢ Detik ke-{0}: Aduk',
      'brew_phase_item_press': 'â€¢ Detik ke-{0}: Tekan',
      'brew_phase_item_wait': 'â€¢ Detik ke-{0}: Tunggu',
      'start_brew_btn': 'MULAI SEDUH',
      'start_brew_label': 'Mulai proses penyeduhan',
      'cancel_brew_btn': 'Batal',
      'pour_circle_instruction': 'Tuang {0} mili, {1} putaran.',
      'pour_center_instruction': 'Tuang di tengah {0} mili selama {1} detik.',
      'stir_instruction': 'Aduk.',
      'press_instruction': 'Tekan perlahan.',
      'open_valve_instruction': 'Buka switch atau keran.',
      'close_valve_instruction': 'Tutup switch atau keran.',
      'pour_fast_instruction': 'Tuang {0} mili air.',
      'wait_instruction': 'Tunggu...',
      'cancel_brew_label': 'Batalkan penyeduhan',
      'finish_brew_btn': 'SELESAI',
      'finish_brew_label': 'Selesai, kembali ke menu utama',
      'brew_complete': 'Waktu seduh selesai. Selamat menikmati kopimu!',
      'action_pour_circle': 'Tuang Memutar',
      'action_pour_center': 'Tuang di Tengah',
      'action_stir': 'Aduk',
      'action_wait': 'Tunggu',
      'action_press': 'Tekan',
      'action_openValve': 'Buka Switch',
      'action_closeValve': 'Tutup Switch',
      'action_pourFast': 'Tuang Langsung',
      'stop_pour': 'Berhenti.',
      'app_lang': 'Bahasa Aplikasi',
      'app_lang_label': 'Pilih Bahasa Aplikasi',
      'app_lang_desc': 'Ubah bahasa antarmuka (teks) aplikasi',
      'gemini_title': 'Provider AI',
      'gemini_desc': 'Untuk menggunakan fitur "Buat Resep dengan AI", salin API Key milikmu dari Google AI Studio atau Groq Console, lalu tempelkan di bawah ini:',
      'gemini_help_title': 'Cara Mendapatkan API Key',
      'gemini_help_content': '1. Buka aistudio.google.com\n2. Login dengan akun Google.\n3. Klik "Get API key" > "Create API key".\n4. Salin kodenya.\n\nCatatan: Layanan ini gratis tanpa perlu kartu kredit.',
      'groq_help_content': '1. Buka console.groq.com/keys\n2. Login dengan akunmu.\n3. Klik "Create API Key".\n4. Salin kodenya (biasanya diawali dengan gsk_).\n\nCatatan: Layanan ini gratis tanpa perlu kartu kredit.',
      'show_password': 'Tampilkan Password',
      'hide_password': 'Sembunyikan Password',
      'show_api_key': 'Tampilkan API Key',

      'gemini_api_key_label': 'Google gemini API key',
      'groq_api_key_label': 'Groq API key',
      'close': 'Tutup',
      'ai_recipe_btn': 'Resep\nAI',
      'ai_recipe_label': 'Buat resep otomatis dengan AI.',
      'ai_title': 'Buat Resep dengan AI',
      'ai_prompt_label': 'Deskripsikan kopi atau seleramu',
      'ai_prompt_hint': 'Contoh: Kopi Gayo, aku suka rasa buah yang manis dan tidak terlalu asam...',
      'ai_generate_btn': 'BUAT RESEP SEKARANG',
      'ai_generating': 'Memikirkan resep terbaik...',
      'ai_error_no_key': 'API Key belum diisi. Silakan isi di menu Pengaturan terlebih dahulu.',
      'ai_error_failed': 'Gagal membuat resep: {0}',
      'edit_btn': 'Edit',
      'delete_btn': 'Hapus',
      'brew_btn': 'Seduh',
      'delete_confirm_title': 'Hapus Resep?',
      'delete_confirm_desc': 'Apakah kamu yakin ingin menghapus resep {0}?',
      'tts_title': 'Suara & Bahasa (TTS)',
      'tts_enable': 'Petunjuk Suara',
      'tts_enable_desc': 'Matikan jika kamu hanya ingin mendengar metronom',
      'tts_channel': 'Saluran Suara',
      'tts_channel_desc': 'Pilih siapa yang akan membacakan aba-aba',
      'tts_channel_app': 'TTS',
      'tts_channel_sr': 'Pembaca Layar',
      'tts_lang': 'Bahasa Suara',
      'tts_speed': 'Kecepatan Suara',
      'tts_pitch': 'Nada Suara (Pitch)',
      'tts_voice': 'Pilihan Jenis Suara',
      'tts_voice_desc': 'Suara yang tersedia bergantung pada mesin HP-mu',
      'tts_speed_changed': 'Kecepatan diubah menjadi {0}',
      'tts_pitch_changed': 'Nada suara diubah',
      'tts_voice_changed': 'Jenis suara diubah',
      'tts_channel_changed': 'Saluran suara berhasil diubah',
      'default': 'Default',
      'desc_hoffmann': 'Metode PERKOLASI modern. Buat galian kecil (sumur) di tengah kopi sebelum menyeduh. Goyangkan perlahan (swirl) saat blooming, dan goyangkan lagi secara memutar di fase akhir untuk mendatarkan kopi.',
      'desc_kasuya': 'Metode PERKOLASI dengan gilingan sangat kasar. 40% air pertama menentukan manis/asam, 60% sisa mengatur kekuatan kopi. Biarkan air benar-benar tuntas menetes ke bawah pada setiap jeda fase.',
      'desc_lance': 'Metode PERKOLASI yang mengandalkan 1 tuangan panjang. Tuang dengan sangat perlahan dan lembut, biarkan air naik pelan-pelan tanpa mengaduk kopi terlalu keras di bagian bawah.',
      'desc_osmotic': 'Metode PERKOLASI lambat (Osmotik). Kunci utamanya: tuang air HANYA di area tengah sebesar koin untuk membangun kubah kopi (dome). JANGAN sampai aliran airmu merusak kubah atau menyentuh dinding kertas saring di pinggir.',
            'desc_rao': 'Metode PERKOLASI ekstraksi tinggi. Wajib mengaduk perlahan dengan sendok saat blooming agar basah merata. Di akhir tuangan, putar alat V60 (Rao Spin) agar ampas menempel rata.',
      'desc_perger': 'Metode PERKOLASI porsi kecil yang intens. Gunakan teknik tuangan cepat melingkar di pinggir untuk menyapu ampas, lalu kembali fokus menembak di tengah.',
      'desc_april': 'Metode PERKOLASI presisi. Di setiap fase, bagilah tuanganmu: pertama melingkar untuk membasahi pinggir, lalu sisanya dituang diam di tengah.',
      'desc_kurasu': 'Metode PERKOLASI all-rounder. Menghasilkan secangkir kopi yang sangat bersih (clean cup). Tuang sisa air tepat setelah air blooming turun sepenuhnya.',
    },
    'en': {
      'grinder_clicks': 'clicks',
      'header_favorites': 'â­ Favorites',
      'header_custom': 'âœ¨ Your Recipes',
      'header_builtin': 'â˜• Standard Recipes',
      'mark_favorite': 'Mark as favorite',
      'remove_favorite': 'Remove from favorites',
      // AUTO GENERATED ID RECIPES
      'desc_key_0': 'Use water at 99Â°C and a medium-fine grind. Create a divot in the center of the coffee bed. Swirl the brewer during the bloom phase and after the final pour to ensure even extraction.\n\nEstimated Flavor Profile: Balanced extraction, optimal sweetness, and high clarity.',
      'desc_key_1': 'Use a coarse grind and 90-92Â°C water. Allow the bed to dry completely before proceeding to the next pour. The first 40% of the water influences acidity and sweetness, and the remaining 60% controls the strength.\n\nFlavor Profile: Clean cup, bright acidity, with a light, tea-like body.',
      'desc_key_2': 'Medium-fine grind. Water at 90-92Â°C. Pour water very slowly, only in a coin-sized area in the center. DO NOT let the water touch the filter paper. Keep the coffee dome intact.\n\nEstimated Flavor Profile: Very sweet (maximum sweetness), with a smooth and rich body, and muted acidity.',
      'desc_key_3': 'Use a low temperature (around 90Â°C) and a coarse grind. Pour slowly in a circular motion without vigorous agitation. A flat-bed dripper is recommended.\n\nFlavor Profile: Very bright acidity, a clean cup, and prominent fruity notes.',
      'desc_key_4': 'Make a divot in the center. Use a high temperature. Perform a \'Rao Spin\' (swirl the dripper in a circular motion) after the bloom and at the end to level the coffee bed and prevent channeling.\n\nEstimated Taste: Balanced extraction (high extraction yield), sweet, minimal astringency.',
      'desc_key_5': 'Classic Hario factory recipe. Very beginner-friendly. Pour slowly in a circular motion from the center outwards, then back to the center.\n\nFlavor Profile: Classic, medium body, prominent acidity, and strong brewing aroma.',
      'desc_key_6': 'God Recipe by Tetsu Kasuya. Temperature 90Â°C. OPEN the valve at the start (percolation). At 65 seconds, CLOSE the valve (immersion). OPEN the valve again at the end. Produces a perfectly balanced extraction.\n\nFlavor Profile: Very sweet, a unique blend of V60 clarity and immersion body.',
      'desc_key_7': 'Medium grind. Pour water first, then add the coffee grounds. Stir after a few moments, then let it steep.\n\nFlavor Profile: Full body, very balanced flavor, and minimal risk of over-extraction.',
      'desc_key_8': 'Medium grind (does not need to be too coarse). Brew for 4 minutes, then stir the coffee crust on the surface. Skim the foam. Wait another 5-8 minutes before pouring, and DO NOT press the plunger to the bottom.\n\nFlavor Profile: Full body yet very clean without grounds, thick texture, and balanced flavor.',
      'desc_key_9': 'Coarse grind. Pour all the water and stir evenly. Let it steep for 4 minutes, then press the plunger down slowly to the bottom.\n\nFlavor Profile: Very thick body, strong aroma, classic gritty texture.',
      'desc_key_10': 'Brew a very strong coffee concentrate. Mix it with steamed or heated milk in a 1:1 ratio.\n\nFlavor Profile: Warm, milky, savory milk notes with a strong coffee character.',
      'desc_key_11': 'Medium-fine grind. Stir immediately with a spoon at the beginning. Let it steep for 5 minutes. Press the plunger ONLY until it touches the water to keep the fine grounds trapped below.\n\nFlavor Profile: Very clean for a French Press, smooth body, slowly extracted sweetness.',
      'desc_key_12': 'Stir vigorously at the beginning and immediately skim the foam in the first minute for even extraction from the start.\n\nFlavor Profile: Thick body with minimal grit, cleaner taste than traditional methods.',
      'desc_key_13': 'Pre-infuse with room temperature water for 1 minute, then pour hot water. This reduces bitterness and enhances the coffee\'s natural sweetness.\n\nFlavor Profile: Reduces sharp acidity and bitterness, highlighting a smoother sweet profile.',
      'desc_key_14': 'Similar to cupping. Brew for 4 minutes, stir gently, skim the foam and crust, wait another 5 minutes before pressing.\n\nFlavor Profile: Nordic roast (light) characteristics, bright acidity, light body, more akin to a cupping bowl.',
      'desc_key_15': '[Method: Standard] Use a paper filter. Low water temperature (80Â°C). Stir quickly for 10 seconds, then press slowly. Do not press until it hisses.\n\nFlavor Profile: Very sweet, low acidity, thick body, similar to espresso concentrate.',
      'desc_key_16': '[Method: Standard] Medium-fine grind. Boiling water. Standard brew (non-inverted). Stir gently, then press slowly at 60 seconds.\n\nFlavor Profile: Clean cup, bright acidity, tastes similar to a V60 pour-over.',
      'desc_key_17': '[Method: Standard] More coffee-efficient. Standard position. Brew for 2 minutes, swirl slightly, let it rest for 30 seconds, then press slowly.\n\nFlavor Profile: Very efficient, sweet, full body, and even extraction without excessive sourness.',
      'desc_key_18': '[Method: Inverted] (MUST be Inverted). Pour water, stir vigorously with a spoon, then attach the cap. At 1:30, carefully flip the brewer onto a cup and press down.\n\nFlavor Profile: Strong body, bold taste, perfect for mixing with milk or drinking black.',
      'desc_key_19': '[Method: Inverted] Shorter brew time, inverted method. Flip at 1:00 and press for 30 seconds.\n\nFlavor Profile: Brighter acidity, clean cup.',
      'desc_key_20': '[Method: Standard] Brew a very strong coffee concentrate (Use a Prismo or Flow Control attachment), then immediately stir with cold milk and ice cubes in a glass.\n\nFlavor Profile: Smooth, creamy, and refreshing milk punch.',
      'desc_key_21': '[Method: Standard] 2023 World Aeropress Championship winning recipe. Low-temperature extraction with intense stirring, then bypassed with hot water at the end.\n\nFlavor Profile: Complex, sweet, bright fruity acidity but with a very silky texture.',
      'desc_key_22': '[Method: Standard] Long 9-minute steep with a V60 grind size. Produces a sweet and even extraction without bitterness.\n\nFlavor Profile: Very high extraction yield (high EY), maximum sweetness, no under-extracted sourness.',
      'desc_key_23': '[Method: Standard] Use inverted or standard method. Boiling water to extract coffee concentrate. Stir evenly, then press over a glass filled with ice chunks.\n\nFlavor Profile: Refreshing, strong initially but melts slowly (refreshing), sweet.',
      'desc_key_24': '[Method: Standard] Very fine grind with very little water, pressed as hard as possible. Produces a thick concentrate similar to espresso.\n\nFlavor Profile: Strong, punchy, creates faux crema (if pressed hard), great for mocktails or milk drinks.',
      'desc_key_25': 'Medium-coarse grind. Dark roast Robusta coffee. Tamp down with the press filter. Pour boiling water. The dripping process takes about 5-6 minutes.\n\nFlavor Profile: Strong bitterness, smokey, very thick (syrupy) and bold body.',
      'desc_key_26': 'A lighter variation. Use medium-fine grind and Arabica beans. Tamp lightly, drip for 4 minutes.\n\nFlavor Profile: Brighter acidity, lighter body.',
      'desc_key_27': 'Use a 1:15 ratio, similar to a standard pour-over, but brewed with the Vietnam Drip. Tamp very lightly.\n\nFlavor Profile: Clean cup, balanced, similar to a slow drip V60.',
      'desc_key_28': 'Modern approach for light roast coffee beans. Extracts sweet and sour flavors cleanly.\n\nFlavor Profile: Cleaner than traditional methods, acidity starts to shine, modern flavor complexity.',
      'desc_key_29': 'Use an Aeropress paper filter on top of the coffee bed before tamping for a more even water distribution.\n\nFlavor Profile: Higher extraction yield, more balanced.',
      'desc_key_30': 'Classic combination of Sweetened Condensed Milk (SCM) and Palm Sugar Syrup. SCM provides the signature \'creamy\' texture of Vietnam Drip, while palm sugar adds a sweet caramel aroma. Pour SCM and palm sugar into the bottom of the glass, brew slowly, stir well, then add ice.\n\nFlavor Profile: Very creamy, sweet palm sugar caramel blends with a strong and thick coffee flavor.',
      'desc_key_31': 'Place a paper filter (Aeropress size) at the bottom of the Phin brewer before adding coffee. Produces an incredibly clean brew with no fine grounds. (Optional: place another paper filter on top of the coffee before tamping for super even extraction).\n\nFlavor Profile: Much cleaner with no grit, reduced body but with clearer flavor clarity.',
      'desc_key_32': 'Designed for specialty coffee beans (Light Roast), the tamping process is less firm to allow optimal water flow.\n\nFlavor Profile: A longer ratio produces a lighter beverage, similar to a strong pour-over.',
      'desc_key_33': 'Rare method: Tamp the coffee with the filter press, pour bloom water, then tamp AGAIN (second tamp) before pouring the rest of the water. Results in a much slower drip rate.\n\nFlavor Profile: Incredible extraction intensity, like espresso, with a very thick body.',
      'desc_key_34': 'Temperature 93Â°C. At minute 4, push the back of a cupping spoon 3 times across the coffee surface (break the crust). Skim the remaining foam. Start slurping at minute 10 when the temperature drops.\n\nFlavor Profile: Pure flavor profile of the coffee beans for defect/quality evaluation purposes.',
      'desc_key_35': 'Home-style cupping. Use two spoons to skim the foam at minute 4.\n\nFlavor Profile: Pure coffee bean flavor without paper filter interference, perfect for comparing 2 different beans.',
      'desc_key_36': 'Focuses on evaluating the coffee flavor when it is very cold at minute 15. The initial phase is the same, but wait much longer.\n\nFlavor Profile: Assesses the coffee flavor at room temperature (highlighting sweetness or alternatively, defects/sourness).',
      'desc_key_37': 'No crust breaking process. The coffee grounds are left to sink slowly to the bottom of the glass on their own. Results in a very clean flavor evaluation.\n\nFlavor Profile: Very clean, slower extraction avoiding excessive astringency.',
      'desc_key_38': 'Medium-fine grind. Pour hot water over the coffee; the drips will immediately hit the ice cubes in the server to lock in volatile aromas.\n\nFlavor Profile: Very sharp, refreshing, and aromatic fruity acidity (floral/fruity).',
      'desc_key_39': 'Similar to Japanese Iced Coffee, but the ice cube ratio is adjusted and the pours are divided to maximize sweetness.\n\nFlavor Profile: Sweeter and more balanced, not overly acidic, with a slightly thicker body.',
      'desc_key_40': 'Adaptation of the 2024 World Brewers Cup 3rd Place recipe. Uses 4 pour phases with decreasing volumes at the end to prevent over-extraction. Produces a balanced and syrupy flavor.\n\nFlavor Profile: Layered flavor, high complexity, elegant aromatic sweetness.',
      'desc_key_41': 'High temperature (93Â°C). Very fast water flow (fast flow). Swirl the dripper quite aggressively at the beginning so all grounds are evenly wetted. Finishes very quickly in 2 minutes.\n\nFlavor Profile: Very transparent fruity acidity, light, similar to coffee-flavored sweet tea.',
      'desc_key_42': 'Consistent pours for flat-bed drippers. Highlights acidity and flavor clarity.\n\nFlavor Profile: Incredible sweetness thanks to the flat bed, consistent extraction, balanced.',
      'desc_key_43': 'Use 85Â°C water and quick center pours to avoid burnt and excessively bitter flavors in dark roast beans.\n\nFlavor Profile: Smooth bitterness, caramel sweetness, without excessive burnt/smokey notes.',
      'desc_key_44': 'Devil Recipe V60 Switch. OPEN the valve at the beginning. MUST use ROOM TEMPERATURE water (cold/normal) for the first 60ml bloom phase. For the rest, use boiling hot water for the immersion phase.\n\nFlavor Profile: Very bold, thick sweet extraction at the start, finished with immersion for body.',
      'desc_key_45': '[Method: Inverted] 2018 World Aeropress Championship winning recipe. Inverted position, vigorous stirring, resulting in a super fruity extraction.\n\nFlavor Profile: Vibrant, bright acidity, clean finish.',
      'desc_key_46': '[Method: Inverted] 2017 Championship recipe. Strong 1:5 ratio at the beginning, topped up with bypass water at the end. Inverted.\n\nFlavor Profile: Round body, balanced, highly recommended for natural processed coffees.',
      'desc_key_47': '[Method: Standard] Standard Aeropress (not inverted). 80Â°C water, let it drip slowly then press very slowly.\n\nFlavor Profile: Complex, dominantly sweet, juicy body.',
      'desc_key_48': '[Method: Standard] Uses a Prismo cap or Flow Control. Full immersion without being inverted.\n\nFlavor Profile: Like home espresso, strong, no premature water leakage.',
      'desc_key_49': '[Method: Standard] High concentrate extraction resembling espresso. Use Prismo/Flow Control and an espresso grind size.\n\nFlavor Profile: Bitter, thick, bold, perfect for mixing with brown sugar or milk.',
      'desc_key_50': '[Method: Standard] Wide ratio and coarse grind for a refreshing, tea-like coffee flavor.\n\nFlavor Profile: Very light, transparent, dominant floral/fruity notes like premium tea.',
      'desc_key_51': '[Method: Standard] Specifically for Robusta coffee. Short extraction with 85Â°C temperature so it\'s not too bitter.\n\nFlavor Profile: Classic Robusta bitterness balanced by a thick texture and sweet nutty notes.',
      'desc_key_52': 'Make a salt cream by frothing sweetened condensed milk, liquid milk/cream, and salt until foamy. Drip the coffee over it. Stir before drinking.\n\nFlavor Profile: An amazing combination of savory saltiness, thick sweetness, and bold coffee bitterness. Umami!',
      'desc_key_53': 'Whip free-range egg yolks with sweetened condensed milk and a little honey until it fluffs into a thick foam. Drip hot coffee over or under it.\n\nFlavor Profile: Very creamy, dessert-like (tiramisu), thick sweetness, without any eggy smell.',
      'desc_key_54': 'A unique Vietnamese combination. Add yogurt to the bottom of the glass, add condensed milk, brew coffee over it, then add ice cubes.\n\nFlavor Profile: Fresh tangy yogurt combined with creamy sweetness and coffee bitterness. Very refreshing.',
      'desc_key_55': 'Vietnam Drip specifically for Arabica beans. Lightly tamped, 92Â°C temperature for a thick yet fruity body.\n\nFlavor Profile: Signature Arabica fruity acidity, body is not as thick compared to Robusta.',
      'desc_key_56': 'Add cocoa powder or chocolate syrup into the condensed milk. Drip the coffee through the chocolate. Stir well.\n\nFlavor Profile: Intense dark chocolate, sweet, thick, like a chocolate coffee candy.',
      'desc_key_57': 'A variant of Vietnamese iced milk coffee (Báº¡c Xá»‰u) with added coconut milk. The proportion of milk and coconut dominates over the coffee for a sweet, savory, and creamy taste.\n\nFlavor Profile: Savory sweet coconut, very creamy, softer background coffee flavor.',
      'extra_key_0': 'Hot Milk (150ml)',
      'extra_key_1': '140ml Additional hot water (Bypass)',
      'extra_key_2': 'Cold Liquid Milk (100ml), Ice Cubes (100g)',
      'extra_key_3': 'Prepare 80 ml hot water in the serving glass (for bypass)',
      'extra_key_4': 'Ice cubes (around 100g)',
      'extra_key_5': 'Sweetened Condensed Milk (30g), Ice Cubes (150g)',
      'extra_key_6': 'Sweetened Condensed Milk (15-20ml), Palm Sugar Syrup (10-15ml), Ice Cubes',
      'extra_key_7': '30 ml sweetened condensed milk',
      'extra_key_8': 'Ice Cubes (100g in server)',
      'extra_key_9': 'Ice Cubes (90g in server)',
      'extra_key_10': 'Additional hot water/ice for bypass',
      'extra_key_11': 'Salt Cream (20ml Milk, 10g Condensed Milk, Pinch of Salt), Ice Cubes (100g)',
      'extra_key_12': 'Egg Yolk (1 unit), Condensed Milk (20g), Honey (1 tsp)',
      'extra_key_13': 'Plain Yogurt (50g), Condensed Milk (15g), Ice Cubes (100g)',
      'extra_key_14': 'Chocolate/Cocoa Syrup (15g), Condensed Milk (20g)',
      'extra_key_15': '40 ml sweetened condensed milk, 60 ml liquid coconut milk, 100 grams ice cubes. (Mix all in the serving glass)',


      'brew_dose': 'Coffee Dose: {0} scoops',
      'brew_grind': 'Grind Size',
      'brew_bean': 'Coffee Bean Type',
      'brew_extra': 'Extra Ingredients',
      'brew_desc_title': 'Recipe Description:',
      'rotations_half': ' and a half',
      'custom_grind_400': 'Very Fine (Espresso)',
      'custom_grind_600': 'Fine (Aeropress)',
      'custom_grind_800': 'Medium (V60 / Kalita)',
      'custom_grind_1000': 'Medium Coarse (Chemex)',
      'custom_grind_1200': 'Coarse (French Press / Switch)',
      'custom_grind_1400': 'Very Coarse (Cold Brew)',
      'custom_bean_blend': 'Blend',
      'custom_bean_bebas': 'Any Bean',
      'custom_recipe_desc': 'Recipe Description',
      'custom_recipe_extra_hint': 'E.g: 15 ml condensed milk, 100 g ice cubes',


      'home_select_method': 'Select Brew Method:',
      'method_v60_desc': 'Pour-over brewing with spiral pours',
      'method_fp_desc': 'Immersion brewing without grounds',
      'method_ap_desc': 'Press brewing using air pressure',
      'method_vd_desc': 'Slow drip brewing (Milk Coffee)',
      'method_cup_desc': 'International coffee evaluation standard',


      'calib_guide': 'Calibration Guide:\n1. Prepare a kettle with water and a scale or measuring cup.\n2. Activate the Metronome Simulation button below.\n3. After the start cue, pour water as usual.\n4. Count how many TICK sounds you hear until the water reaches your target volume.\n5. Try pouring in a circle, and count how many TICK sounds it takes to complete one full rotation.\n6. Enter those numbers into the fields below!',
      'calib_header': 'Brewing Equipment & Flow Rate Calibration',
      'calib_q1': 'What is the volume/weight of your measuring cup or target in ml/grams?',
      'calib_q2': 'Turn on the metronome, then pour water. How many seconds (beats) does it take to reach the target?',
      'calib_q3': 'Typically, how many seconds do you need to complete 1 full circle rotation (spiral) when pouring?',
      'toggle_api_key': 'Show or hide API Key',
      'restore_success': 'Default recipes restored successfully!',
      'calib_grinder_select': 'Select Your Grinder:',
      'calib_grinder_title': 'Select Grinder',
      'calib_grinder_manual': 'Manual Grinder',
      'calib_grinder_electric': 'Electric Grinder',
      'calib_spoon_q': 'What is the capacity of your measuring scoop in grams?',
      'calib_sim_btn': 'Metronome Simulation (Play Countdown)',
      
      'ai_greet_edit': "Hi! I see you're editing the recipe '{0}'. What would you like to change?",
      'ai_greet_new': "Hi! What kind of brew recipe would you like to create today?",
      'ai_error_general': "Sorry, something went wrong while processing your request.",
      'ai_hint': "Type a message...",
      'ai_voice_note': '\u{1F399}\u{FE0F} [Voice Message]',
      'ai_apply_btn': "Apply to Form",
      'ai_send_label': "Send text message",
      'ai_record_start_label': "Start voice recording",
      'ai_record_stop_label': "Stop recording",
      'ai_coffee': "Coffee",
      'ai_water': "Water",
      'ai_time': "Time",
      
      'tts_preview_btn': "Test Voice Preview",
      'tts_preview_text': "This is a sample voice from the current settings.",
      
      'action_swirl': 'Swirl gently',
      'action_cap': 'Attach Cap',
      'action_flip': 'Flip onto cup',
      
      'ai_chat_title': 'Design with AI',

      'app_title': 'SenseBrew',
      'settings_menu': 'App Settings Menu',
      'calibrate_flow_rate': 'Brewing Equipment & Flow Rate Calibration',
      'settings_title': 'Settings',
      'settings_restore_title': 'Restore Default Recipes',
      'settings_restore_sub': 'Restore deleted built-in recipes',
      
      'theme_title': 'App Theme',
      'calibrated_status': 'Device ready. Flow rate: {0} ml per second',
      'uncalibrated_status': 'Flow rate not calibrated.',
      'calibrated_btn': '{0} ml/second',
      'uncalibrated_btn': '(Required)',
      'custom_recipe_btn': 'Custom\nRecipe',
      'custom_recipe_label': 'Create a custom brew recipe.',
      'recipe_label': '{0} recipe. {1} grams of coffee. {2} milliliters of water.',
      'calib_title': 'Brewing Equipment & Flow Rate Calibration',
      'stop_metronome': 'Stop Metronome',
      'start_metronome': 'Play Metronome',
      'save_calib': 'SAVE CALIBRATION',
      'save_calib_label': 'Save calibration results',
      'save_success': 'Calibration saved successfully.',

      'pour_calc_title': 'Pour Calculator',
      'pour_calc_desc': 'Free pour assistant. Enter the amount of water (ml) you want to pour, and the app will calculate and guide the timing based on your kettle\'s calibration.',
      'pour_calc_target': 'Pour Target (ml)',
      'pour_calc_est': 'Estimated Time: {0} seconds',
      'pour_calc_start': 'Start Pour',
      'pour_calc_stop': 'Stop',
      'pour_calc_ready': 'Get ready, pouring in',

      'reduce': 'Reduce to {0} {1}',
      'add': 'Increase to {0} {1}',
      'custom_title': 'Create Custom Recipe',
      'recipe_name': 'Recipe Name',
      'recipe_note': 'Brewing Notes & Rules',
      'coffee_grams': 'Coffee (grams)',
      'total_water': 'Total Water (milliliters)',
      'total_time': 'Total Time (seconds)',
      'phases_title': 'Brewing Phases',
      'start_sec': 'Start at Second',
      'water_ml': 'Water (ml)',
      'add_phase': 'Add Phase',
      'delete_phase': 'Delete Phase',
      'save_recipe': 'Save Recipe',
      'save_as_new': 'Save as New',
      'save_overwrite': 'Overwrite Existing',
      'save_recipe_success': 'Recipe saved successfully!',
      'brew_sec': 'Second: {0}\n{1}',
      'brew_title': 'Brewing Now',
      'note_label': 'Add Note',
      'note': 'Note',
      'brew_phases': 'Brewing Phases:',
      'brew_phase_item_circle': 'â€¢ Second {0}: Pour {1} ml ({2} rotations)',
      'brew_phase_item_center': 'â€¢ Second {0}: Pour {1} ml ({2} seconds)',
      'brew_phase_item_stir': 'â€¢ Second {0}: Stir',
      'brew_phase_item_press': 'â€¢ Second {0}: Press',
      'brew_phase_item_wait': 'â€¢ Second {0}: Wait',
      'start_brew_btn': 'START',
      'start_brew_label': 'Start brewing',
      'cancel_brew_btn': 'CANCEL',
      'pour_circle_instruction': 'Pour {0} mili, {1} rotations.',
      'pour_center_instruction': 'Center pour {0} mili for {1} seconds.',
      'stir_instruction': 'Stir.',
      'press_instruction': 'Press slowly.',
      'open_valve_instruction': 'Open the valve.',
      'close_valve_instruction': 'Close the valve.',
      'pour_fast_instruction': 'Pour {0} mili of water.',
      'wait_instruction': 'Wait...',
      'cancel_brew_label': 'Cancel brewing',
      'finish_brew_btn': 'DONE',
      'finish_brew_label': 'Finish brewing',
      'brew_complete': 'Brewing Complete!',
      'action_pour_circle': 'Spiral Pour',
      'action_pour_center': 'Center Pour',
      'action_stir': 'Stir',
      'action_wait': 'Wait',
      'action_press': 'Press',
      'action_openValve': 'Open Valve',
      'action_closeValve': 'Close Valve',
      'action_pourFast': 'Direct Pour',
      'stop_pour': 'Berhenti.',
      'app_lang': 'Language',
      'app_lang_label': 'App Language',
      'app_lang_desc': 'Select the language for the app',
      'gemini_title': 'AI Provider',
      'gemini_desc': 'To use the "Create Recipe with AI" feature, copy your API Key from Google AI Studio or Groq Console, and paste it below:',
      'gemini_help_title': 'How to get a Gemini API Key?',
      'gemini_help_content': '1. Go to aistudio.google.com\n2. Log in with your Google account.\n3. Click "Get API key" > "Create API key".\n4. Copy the code.\n\nNote: This service is free and does not require a credit card.',
      'groq_help_content': '1. Go to console.groq.com/keys\n2. Log in with your account.\n3. Click "Create API Key".\n4. Copy the code (usually starts with gsk_).\n\nNote: This service is free and does not require a credit card.',
      'show_password': 'Show Password',
      'hide_password': 'Hide Password',
      'show_api_key': 'Show API Key',

      'gemini_api_key_label': 'Google Gemini API Key',
      'groq_api_key_label': 'Groq API Key',
      'close': 'Close',
      'ai_recipe_btn': 'Use Recipe',
      'ai_recipe_label': 'Generated Recipe',
      'ai_title': 'AI Assistant',
      'ai_prompt_label': 'What kind of coffee do you want?',
      'ai_prompt_hint': 'E.g: Sweet iced coffee using V60',
      'ai_generate_btn': 'Generate Recipe with AI',
      'ai_generating': 'Generating recipe...',
      'ai_error_no_key': 'API Key is empty. Please fill it in Settings first.',
      'ai_error_failed': 'Failed to create recipe: {0}',
      'edit_btn': 'Edit',
      'delete_btn': 'Delete',
      'brew_btn': 'Brew',
      'delete_confirm_title': 'Delete Recipe?',
      'delete_confirm_desc': 'Are you sure you want to delete the recipe {0}?',
      'tts_title': 'Voice & Language (TTS)',
      'tts_enable': 'Voice Instructions',
      'tts_enable_desc': 'Turn off if you only want to hear the metronome',
      'tts_channel': 'Audio Channel',
      'tts_channel_desc': 'Select who will read the instructions',
      'tts_channel_app': 'TTS',
      'tts_channel_sr': 'Screen Reader',
      'tts_lang': 'Voice Language',
      'tts_speed': 'Voice Speed',
      'tts_pitch': 'Voice Pitch',
      'tts_voice': 'Voice Selection',
      'tts_voice_desc': 'Available voices depend on your phone\'s engine',
      'tts_speed_changed': 'Speed changed to {0}',
      'tts_pitch_changed': 'Voice pitch changed to {0}',
      'tts_voice_changed': 'Voice changed to {0}',
      'tts_channel_changed': 'Audio channel changed',
      'default': 'Default',
      'desc_hoffmann': 'James Hoffmann\'s ultimate V60 recipe. Uses a swirl during bloom and at the end. Medium-fine grind. Focuses on even extraction and high yield.',
      'desc_kasuya': 'Tetsu Kasuya\'s 4:6 method. Coarse grind. Divides water into 40% (for sweetness/acidity balance) and 60% (for strength).',
      'desc_lance': 'PERCOLATION method relying on 1 long pour. Pour very slowly and gently, letting the water rise slowly without disturbing the coffee bed at the bottom.',
      'desc_osmotic': 'Osmotic Flow method. Pour slowly only in the center to maintain the coffee dome. Maximizes sweetness and minimizes bitterness.',
            'desc_rao': 'Scott Rao\'s method. Uses a single long pour after bloom, followed by a \'Rao Spin\' to level the bed and prevent channeling.',
      'desc_perger': 'Matt Perger\'s V60 recipe. Fine grind. Uses a tap to level the bed before brewing. Two pours. High extraction yield.',
      'desc_april': 'A recipe specifically for the April Pour-Over Brewer. Uses a coarse grind and a flat bed. Two circular pours and two center pours.',
      'desc_kurasu': 'An all-rounder PERCOLATION method. Produces a very clean cup. Pour the remaining water right after the blooming water has fully drained.',
    },
  };

  static String str(String lang, String key, [List<String>? args]) {
    String text = _strings[lang]?[key] ?? _strings['id']?[key] ?? key;
    
    // Parse dual-language payloads like "ID: ... || EN: ..."
    if (text.contains('ID: ') && text.contains('|| EN: ')) {
      final parts = text.split('|| EN: ');
      if (lang == 'id') {
        text = parts[0].replaceAll('ID: ', '').trim();
      } else {
        text = parts[1].trim();
      }
    }

    if (args != null) {
      for (int i = 0; i < args.length; i++) {
        text = text.replaceAll('{'+i.toString()+'}', args[i]);
      }
    }
    return text;
  }
}





